### ISSUE TITLE
py importlib-resources - ERROR: No matching distribution found for zipp>=3.1.0; python_version < "3.10"

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#349] opened 2021-11-07 15:12 UTC
`nix-shell -p nixFlakes --run "nix run mach-nix#gen.python.ipython.importlib-resources.zipp --show-trace "`

```
warning: unknown setting 'experimental-features'
warning: --- Large path -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
dumping very large path (> 256 MiB); this may run out of memory
builder for '/nix/store/9sm17fmcf5a97bd9lif6i64wx35hf1gk-python3.8-importlib-resources-5.1.4.drv' failed with exit code 1; last 10 log lines:
  configuring
  no configure script, doing nothing
  building
  no Makefile, doing nothing
  installing
  Executing pipInstallPhase
  /build/dist /build
  Processing ./importlib_resources-5.1.4-py3-none-any.whl
  ERROR: Could not find a version that satisfies the requirement zipp>=3.1.0; python_version < "3.10" (from importlib-resources)
  ERROR: No matching distribution found for zipp>=3.1.0; python_version < "3.10"
cannot build derivation '/nix/store/n30pfr8fiwaaja6hq1rgknphc46cvcq5-python3-3.8.9-env.drv': 1 dependencies couldn't be built
error: --- Error --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
build of '/nix/store/n30pfr8fiwaaja6hq1rgknphc46cvcq5-python3-3.8.9-env.drv' failed
```

What is the issue?
How to make it work?

**Comment by TyberiusPrime** [comment] 2021-11-19 15:22
I'm running into the same issue after forwarding my ecosystem date to yesterday.

**Comment by TyberiusPrime** [comment] 2021-11-23 14:34
So, on the premise that mach-nix is failing to pick up the zipp dependency, 
I started adding it to the build inputs, first of importlib-resources, then of what ever would complain,
netting me this
```
_."importlib-resources".buildInputs.add =[pkgs.python38Packages.zipp];
_."jsonschema".buildInputs.add =[pkgs.python38Packages.zipp];
_."nbformat".buildInputs.add =[pkgs.python38Packages.zipp];
_."nbclient".buildInputs.add =[pkgs.python38Packages.zipp];
```
but now, I'm at 
```
 > Found duplicated packages in closure for dependency 'six':
       >   six 1.15.0 (/nix/store/wb6630cfygi775rvy4r68l5clvlll0c5-python3.8-six-1.15.0/lib/python3.8/site-packages)
       >   six 1.16.0 (/nix/store/l615fgqh3bwgrjnz177vlazj08vd98cs-python3.8-six-1.16.0/lib/python3.8/site-packages)
 ```

**Comment by TyberiusPrime** [comment] 2021-11-23 15:37
i think this is a duplicate of #287

**Comment by DavHau** [comment] 2021-11-23 15:45
Looks like it. `distlib` is dead and should be replaced with `packaging`. I'll close this in favor of the other issue.

**Closed by DavHau** 2021-11-23 15:45 UTC
