### ISSUE TITLE
py jupyter-telemetry /  jhsingle-native-proxy # ERROR: Could not find a version that satisfies the requirement ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10" (from ruamel-yaml)

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#279] opened 2021-05-15 17:32 UTC
nix-shell -p nixFlakes --run "nix run mach-nix#gen.python.ipython.jhsingle-native-proxy --show-trace "

regarding:
- jupyter-telemetry ->  ruamel.yaml

adding 
ruamel.yaml.clib>=0.1.2 has no effect

```
warning: unknown setting 'experimental-features'
warning: --- Large path --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
dumping very large path (> 256 MiB); this may run out of memory
warning: unknown setting 'experimental-features'
trace: 
applying fix 'no-rust-build' (nativeBuildInputs) for cryptography:3.3.2

warning: unknown setting 'experimental-features'
builder for '/nix/store/5nbmqydwypdmmfqwl4djhympvbvwnlyb-python3.8-ruamel.yaml-0.17.4.drv' failed with exit code 1; last 10 log lines:
  configuring
  no configure script, doing nothing
  building
  no Makefile, doing nothing
  installing
  Executing pipInstallPhase
  /build/dist /build
  Processing ./ruamel.yaml-0.17.4-py3-none-any.whl
  ERROR: Could not find a version that satisfies the requirement ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10" (from ruamel-yaml)
  ERROR: No matching distribution found for ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10"
cannot build derivation '/nix/store/faaq6zpy13dq0vpz3qxpx6g7jpg6vh4y-python3-3.8.8-env.drv': 1 dependencies couldn't be built
error: --- Error ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
build of '/nix/store/faaq6zpy13dq0vpz3qxpx6g7jpg6vh4y-python3-3.8.8-env.drv' failed
```

---

works for 
ref="refs/tags/3.1.1" / different pypi

---

works with 
ruamel.yaml<=0.16.12

**Comment by DavHau** [comment] 2021-06-12 17:24
I just noticed https://github.com/DavHau/mach-nix/issues/287 is a duplicate of this. Closing the current issue as I already commented on the other one.

**Closed by DavHau** 2021-06-12 17:24 UTC
